video_path: uploads/Git_GitHub_Tutorial_Visualized_Git_Course_for_Beginner_Professional_Developers_in_2024.mp4
video_title: Git___GitHub_Tutorial___Visualized_Git_Course_for_Beginner___Professional_Developers_in_2024
youtube_url: https://www.youtube.com/watch?v=S7XpTAnSDL4&t=2740s&pp=ygUMZ2l0IHR1dG9yaWFs0gcJCa4KAYcqIYzv
split_timestamps:
- 00:02:03
- 00:04:07
- 00:05:55
- 00:07:46
- 00:14:13
- 00:18:25
- 00:26:35
- 00:30:35
- 00:42:27
- 00:55:50
- 01:11:07
transcript_path: uploads/Git___GitHub_Tutorial___Visualized_Git_Course_for_Beginner___Professional_Developers_in_2024_transcript_9s.pkl
